version: "3.8"

services:
  builder:
    image: klakegg/hugo:0.111.3
    command: --verbose
    environment:
      - HUGO_DESTINATION=/build/blog
      # For maximum backward compatibility with Hugo modules:
      - HUGO_ENV=production
      - HUGO_ENVIRONMENT=production
    volumes:
      - ./src:/src:rw
      - ./build/blog:/build/blog:rw

  blog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build/blog:/blog:rw
