name: Build HUGO website

on:
  # Runs on pull requests to check that the website is building without errors
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          source: ./src
          target: ./build/blog
          env: production
